version: "3.9"

services:
  node-cli:
    image: node:18
    build:
      context: "."
      dockerfile: "./Dockerfile"
    volumes:
      - "./:/app"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
